### ISSUE TITLE
Icon is blurry on some linux distributions

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#159]
Looks like a gnome-specific problem.

Electron Discuss topic: https://discuss.atom.io/t/blurry-icon-on-linux-specific-distribution/30816

It will probably be fixed with Installers (#100) but it would still be a bug with portable versions.
#### elementary os: 0.3.2

![capture du 2016-08-19 12 51 08](https://cloud.githubusercontent.com/assets/1311607/17807555/b05e5074-660b-11e6-973a-3fc344a1f6f9.png)
#### ubuntu gnome 16.04 (gnome 3.18)

![cqdvbvewaaasehw](https://cloud.githubusercontent.com/assets/1311607/17807579/cc96922e-660b-11e6-933e-ff3f7b8215e6.jpg)

**Comment by YurySolovyov** [comment]
launching executable from `build` dir on Ubuntu 16.04:

![image](https://cloud.githubusercontent.com/assets/2168518/17807649/a1b4520e-6614-11e6-8f97-f8c5b9e77e81.png)

Not sure if it is same issues though

**Comment by KeitIG** [comment]
@YurySolovyov Icon is ok by my side for builds. Is it the same when you launch museeks from your dev repository ?

**Comment by YurySolovyov** [comment]
Yeah, same - no musseks icon

**Comment by KeitIG** [comment]
What is your desktop environment ?

**Comment by YurySolovyov** [comment]
Unity 7 + Arc theme

Maybe re-try it with default theme?

**Comment by YurySolovyov** [comment]
For the record: seems fine on Mint 18 
![image](https://cloud.githubusercontent.com/assets/2168518/17820298/d10224d8-6654-11e6-9ea8-7df2d962de6d.png)

**Comment by stelad000** [comment]
for the unkown distribution in the second picture, it's ubuntu gnome 16.04 (gnome 3.18)

**Comment by esarandon** [comment]
Same issue here on ubuntu gnome 16.04 (gnome 3.18)

**Comment by bil-elmoussaoui** [comment]
To fix the icon blurry issue you should add this to the desktop file : `StartupWMClass=museeks`. You can find why i chose `musseks` using  `xprop WM_CLASS` the mouse cursor will change and then click on the musseks application window. The WM_CLASS is used on almost every distro to detect the launched application and associate the app to it's desktop file (which means the showing the right icon).
One more issue that should be fixed too, is to move the icon from `Icon=/opt/museeks/resources/app/src/images/logos/museeks.png` and put it somewhere here `/usr/share/icons/hicolor/xx/apps/` the xx is the size of the icon. This way you can provide more than one size of the icon, which will make it looks better on smaller/bigger screens.  Once the icons are installed there, you change the icon line from `Icon=/opt/museeks/resources/app/src/images/logos/museeks.png` to `Icon=museeks`
The best thing is to provide different size of svg icons instead of png icons as those icons are scalable (this might help to have a better visual for the icons on a dock as the icons are resized when there's more than one application opened)

**Comment by KeitIG** [comment]
Thanks for the informations, this is what I was afraid about. This means we'll not be able to fix this on portable versions.

I'll close this with a wontfix label once the installers feature will be out.

Ref #100

**Comment by KeitIG** [comment]
Has been solved by installers.
