### ISSUE TITLE
Trivial UX and user-feedback improvements

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#187]
Before releasing 0.7.0, Museeks needs some refining:

- [x] Add a notification when tracks are succesfully added to a playlist
- [x] Add a link to Library from EmptyPlaylist
- ...

**Comment by YurySolovyov** [comment]
I wonder if we can make notifications look more like [Android toasts](https://material.google.com/components/snackbars-toasts.html#)

**Comment by KeitIG** [comment]
All of this is about to change until 1.0, so every proposition is welcome.

I had also in mind to differentiate system notification and intern notification.

**Comment by Suriteka** [comment]
Change the muted icon when the sound is muted.

**Comment by YurySolovyov** [comment]
I think it would be ok to just steal notifications style from Android:
![image](https://cloud.githubusercontent.com/assets/2168518/18046439/98b98c40-6de0-11e6-9fd7-bb340af8095a.png)
Current style is somewhat hard to notice since it is white on white.
We just need to make sure our messages are simple and concise.

**Comment by YurySolovyov** [comment]
Well, maybe not literally steal, but show notifications at the bottom, centered, with noticeable look.
