### ISSUE TITLE
Player should be called from actions, not reducers

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#271]
- Definitely not a trivial one
- Because:
    - it's an anti-pattern and should be called in actions
    - it's terrible to deal with audio errors
- Will lead to #270

**Comment by KeitIG** [comment]
Ok, so let's talk about redux-thunk,

> @YurySolovyov We don't use actions creators atm, so I don't see how it would be useful to you

What problems are you trying to solve exactly with `redux-thunk` ?

**Comment by YurySolovyov** [comment]
@KeitIG well, it allows you to get current app state via `getState` function passed via argument to action creators.

> We don't use actions creators atm, so I don't see how it would be useful to you

Right, but we don't use traditional Flux either, so it would be actually more idiomatic for Redux to start using them. [Redux docs on the matter](http://redux.js.org/docs/basics/Actions.html#action-creators)

What `redux-thunk` allows you to do, is to make action creators return functions instead of returning action itself.

`redux-thunk` passes `dispatch` and `getState` functions to your action creators so you can dispatch action when some async operation completes, and calling `getState` at this point is not considered as anti-pattern AFAIK.

**Comment by KeitIG** [comment]
> it would be actually more idiomatic for Redux to start using them

I'm not sure about that. I mean, create a function which return an object looks like an overkill for me, as, for most of the actions, it only dispatch one specific event. That's a personal thought though, what do you think ?

> redux-thunk passes dispatch and getState

It passes getState in a "native" way ? No specific method we have to implement ?

**Comment by YurySolovyov** [comment]
> It passes getState (so the whole state of the app) in a "native" way ? No specific method we have to implement ? 

Not sure what you mean. `getState` gives you the latest state as if it was direct reference in reducer for example.

> I'm not sure about that. I mean, create a function which return an object looks like an overkill for me, as, for most of the actions, it only dispatch one specific event. That's a personal thought though, what do you think ?

This makes these functions easily testable, since they are so simple.
I think Redux docs are the best evidence of that.

**Comment by KeitIG** [comment]
> This makes these functions easily testable

Fair. But if they don't exist, they don't need to be tested. :stuck_out_tongue_closed_eyes: 

> getState gives you the latest state as if it was direct reference in reducer for example.

Just saw it was a middleware from Dan Abramov, so I'm ok with that if this saves us tons of time.

**Comment by KeitIG** [comment]
Should I understand that using `store.dispatch()` is wrong ? :fearful:

**Comment by YurySolovyov** [comment]
Not really, it is just `Flux`-y

**Comment by KeitIG** [comment]
Good to know. It made the transition to redux smoother though.

**Comment by KeitIG** [comment]
For actions creators, should we create an issue for them so ? Or make everything here ?

**Comment by YurySolovyov** [comment]
Yeah, it is actually the last Flux-ism I know we have, even though we don't use Flux for some time already
