### ISSUE TITLE
Access to player que and database

### ISSUE THREAD

**Issue by demil** [KeitIG/museeks#309]
Hi, i would like to make mobile app from which i could control museeks player and i would really appreciate help because i am little confused with redux and react structure.

I just want to know where i need to put script which will contains all socket.io logics and will have access to app, player and database, from which i could change states of it from all routes when app is active.

Thank you very much

**Comment by KeitIG** [comment]
Hello and thanks for your interest!

We do not currently expose any API to a certain port, because we never thought about it. It would not be complicated though, we could imagine an API endpoint or something created by the main processus, then dispatche them to the renderer process, and you could just send post message on it.

But I have no Idea about how secure ans how reliable it would be (you would need to manually open a port on the computer running Museeks)

**Comment by KeitIG** [comment]
@demil Would https://github.com/KeitIG/museeks/issues/324 solve your issue ?
