### ISSUE TITLE
Add minimize/maximize window controls

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#41]
without destroying design, that'd be great.

**Comment by KeitIG** [comment]
Waiting for https://github.com/FortAwesome/Font-Awesome/issues/1582

**Comment by WaynePhipps** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/1582#issuecomment-21042857

Hi guys, 

I don't understand the comment

> Waiting for FortAwesome/Font-Awesome#1582

Wondering what you're waiting for here? Is there a metric or milestone involved?

The issue dates back to July 2013 and seems to have lots of support. Just wondering on the likelihood of this being completed any-time in the next 6 months?

Is there some help the community can provide?

**Comment by YurySolovyov** [comment]
[`octicons`](https://octicons.github.com/) seem to have:
- [`.octicon-dash`](https://octicons.github.com/icon/dash/) for minimize
- [`.octicon-link-external`](https://octicons.github.com/icon/link-external/) for maxmize
- [`.octicon-x`](https://octicons.github.com/icon/x/) for close

Though this would add package (does not seem to be a big deal) + need to figure out how to add only what we use instead of using the whole package (some webpack tweaks?).
Might also need to do some experiments to make sure it looks consistent enough.

**Comment by KeitIG** [comment]
quick idea: make an option to have electron `frame` at true. There would be just some CSS tweaks to do (borders to remove)

**Comment by KeitIG** [comment]
https://materialdesignicons.com/

**Comment by KeitIG** [comment]
Things are being unlocked and these icons will be released in FA 4.7.0

**Comment by KeitIG** [comment]
On the road :]

**Comment by KeitIG** [comment]
FA 4.7.0 is out, I'll do that soon

**Comment by YurySolovyov** [comment]
@KeitIG I tried it, had some issues with empty cover icon, I thought you might want to know.

**Comment by dkniffin** [comment]
Alright, got it in there: 
![image](https://cloud.githubusercontent.com/assets/1680080/21945775/36cc1e58-d9ab-11e6-8156-13d9f4064135.png)

I'll make a PR
