### ISSUE TITLE
Sound volume should be integrated with OS

### ISSUE THREAD

**Issue by likern** [KeitIG/museeks#420]
I'm testing your music application and found out that it's volume bar is completely different with system volume.

I think it should be integrated as I can lower system volume (or even mute) but museeks's bar will show I'm at 100% sound level.

I think if I change system volume, application's volume bar should be reflected accordingly and vice versa.
![screenshot from 2018-03-11 15-41-00](https://user-images.githubusercontent.com/842306/37253457-0eb4ea0a-2543-11e8-8374-3e22152efc68.png)

**Comment by SirWindfield** [comment]
That's a design decision. It works in almost every other music player I have tried too that way.
<img width="1280" alt="screen shot 2018-03-17 at 23 19 48" src="https://user-images.githubusercontent.com/5113257/37560504-be123200-2a39-11e8-88cc-cf0576792e93.png">
Here is iTunes, one of the most popular ones. It has the same behaviour.
I actually prefer it that way because you can tweek the player volume to match your system's master volume that way.

**Comment by likern** [comment]
What about adding some preference choice, if it's not hard to implement. Like "Use system volume" selector? To give more options and tweaks.

**Comment by KeitIG** [comment]
I agree with everything @SirWindfield said. I am trying to understand your usecase though: when willing to change the volume of my laptop, I use the global shortcut for it, not Museeks. 
Using Museeks to change a global settings looks weird to me.

Electron ref: https://github.com/electron/electron/issues/1976
